%%{init: {'theme':'default','themeVariables':{'fontSize':'16px'},'flowchart':{'nodeSpacing':28,'rankSpacing':30,'padding':14}}}%%
flowchart LR
  U[用户] --> L1((登录))
  U --> L2((退出登录))
  S[系统] --> L3((获取用户信息))
  S --> L4((角色首页分配))
  S --> L5((菜单与路由鉴权))
