%%{init: {'theme':'default','themeVariables':{'fontSize':'16px'},'flowchart':{'nodeSpacing':28,'rankSpacing':30,'padding':14}}}%%
flowchart LR
  A[管理员] --> R1((查看角色列表))
  A --> R2((新增角色))
  A --> R3((编辑角色))
  A --> R4((删除角色))
