%%{init: {'theme':'default','themeVariables':{'fontSize':'16px'},'flowchart':{'nodeSpacing':28,'rankSpacing':30,'padding':14}}}%%
flowchart LR
  A[管理员/教师] --> D1((查看统计卡片))
  A --> D2((查看通知区))
  A --> D3((查看待办区))
