%%{init: {'theme':'default','themeVariables':{'fontSize':'16px'},'flowchart':{'nodeSpacing':28,'rankSpacing':30,'padding':14}}}%%
flowchart LR
  F[财务管理员/管理员] --> RB1((查询报销单))
  F --> RB2((查看报销详情))
  F --> RB3((审批通过))
  F --> RB4((审批拒绝并填原因))
  F --> RB5((导出报销数据))
