%%{init: {'theme':'default','themeVariables':{'fontSize':'16px'},'flowchart':{'nodeSpacing':28,'rankSpacing':30,'padding':14}}}%%
flowchart LR
  A[管理员/教师] --> AC1((查询成果))
  A --> AC2((查看成果详情))
  A --> AC3((删除成果))
  A --> AC4((导出成果数据))
