%%{init: {'theme':'default','themeVariables':{'fontSize':'16px'},'flowchart':{'nodeSpacing':28,'rankSpacing':30,'padding':14}}}%%
flowchart LR
  A[管理员/教师] --> PP1((查看流程阶段))
  A --> PP2((切换阶段查看详情))
  A --> PP3((上传阶段附件))
  A --> PP4((提交当前阶段))
  A --> PP5((预览/下载附件))
