%%{init: {'theme':'default','themeVariables':{'fontSize':'16px'},'flowchart':{'nodeSpacing':28,'rankSpacing':30,'padding':14}}}%%
flowchart LR
  R[审批人/管理员] --> AP1((查询申请单))
  R --> AP2((查看申请详情与记录))
  R --> AP3((通过申请))
  R --> AP4((驳回申请))
  R --> AP5((导出申请数据))
